site_name: Pepepri IKB
site_url: https://alinasergeeva6.github.io/pepepri-docs/

theme:
  name: material
  logo: images/Pepperi-Logo-Green.png
  favicon: images/Pepperi-circle-green.png
  features:
    - navigation.indexes
    - content.code.copy

extra_css:
  - css/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences