backend:
  name: github
  repo: AlinaSergeeva6/pepepri-docs
  branch: main
  app_id: "Ov23ligXdRqjgMmcWa2h"

media_folder: "/images"
public_folder: "/images"

collections:
  - name: "docs"
    label: "Pepperi Knowledge Base"
    folder: "docs"
    create: true
    nested:
      depth: 5
    fields:
      - {label: "Head", name: "title", widget: "string", required: false}
      - {label: "Article", name: "body", widget: "markdown"}